import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import cron from "node-cron";
import { GoogleGenAI } from "@google/genai";
import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";

// Initialize Firebase Admin
// Note: In this environment, we usually rely on environmental credentials 
// or the provided firestore config. Since we are in AIS, we can use the config.
import firebaseConfig from "./firebase-applet-config.json";

const app = express();
const PORT = 3000;

// Initialize Admin SDK
// AIS typically provides a way to interact with Firestore via admin sdk if properly configured
// For this environment, we'll assume the default credentials are available or we use the project ID
initializeApp({
  projectId: firebaseConfig.projectId,
});

const db = getFirestore();

async function generateAndSaveArticles(biDailyOnly = false) {
  console.log(`Starting ${biDailyOnly ? 'mid-day Bi-Daily' : 'daily'} article generation task...`);
  try {
    const userBlogsRef = db.collection('user_blogs');
    let q = userBlogsRef.where('autoPublish', '==', true);
    
    if (biDailyOnly) {
      q = q.where('schedule', '==', 'Bi-Daily');
    } else {
      q = q.where('schedule', 'in', ['Daily', 'Bi-Daily']);
    }

    const snapshot = await q.get();
    
    if (snapshot.empty) {
      console.log("No blogs scheduled for auto-publish at this time.");
      return;
    }

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

    for (const doc of snapshot.docs) {
      const blog = doc.data();
      console.log(`Generating massive article for blog: ${blog.name} (User: ${blog.userId})`);

      const prompt = `Write an EXTENSIVE, high-quality, and professional blog post for a blog titled "${blog.name}". 
      Topic: ${blog.topic || 'General Technology'}. 
      Keywords: ${blog.keywords || 'none'}. 
      Tone: ${blog.tone || 'Professional'}. 
      Language: ${blog.language || 'Arabic'}. 
      
      CRITICAL REQUIREMENTS:
      1. Word Count: The article MUST be at least 1200 words long. Be very descriptive and go into deep detail.
      2. Structure: 
         - A catchy, SEO-optimized title.
         - A compelling introduction.
         - Multiple detailed sections with descriptive <h2> and <h3> subheadings.
         - Use bullet points or numbered lists where appropriate for readability.
         - A comprehensive conclusion with a final thought.
      3. Backlink: You MUST include exactly one HTML hyperlink (<a href="${blog.url || '#'}">anchor text</a>) to the blog's homepage. The anchor text should be natural and contextually relevant.
      4. SEO: Naturally integrate the keywords throughout the text, including in at least one subheading.
      5. Output Format: Return ONLY a valid JSON object with "title" and "content" keys. The "content" value MUST be raw HTML. Do not include markdown code blocks.
      
      Target Audience: People interested in ${blog.topic || 'the blog topic'}.`;

      try {
        const response = await ai.models.generateContent({
          model: "gemini-1.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json"
          }
        });
        
        const text = response.text;
        const { title, content } = JSON.parse(text);

        // Save to articles collection
        await db.collection('articles').add({
          title,
          content,
          blogId: blog.blogId,
          blogName: blog.name,
          userId: blog.userId,
          status: 'draft',
          isAutoGenerated: true,
          seoScore: Math.floor(Math.random() * 20) + 80, // Simulated SEO score for UI
          createdAt: FieldValue.serverTimestamp()
        });

        console.log(`Successfully generated and saved 1000+ word article for ${blog.name}`);
      } catch (err) {
        console.error(`Error generating article for ${blog.name}:`, err);
      }
    }
  } catch (error) {
    console.error("Cron job error:", error);
  }
}

// Schedule task at 00:00 every day (Daily and Bi-Daily)
cron.schedule("0 0 * * *", () => {
  generateAndSaveArticles();
});

// Schedule task at 12:00 every day (Bi-Daily only)
cron.schedule("0 12 * * *", () => {
  console.log("Triggering 12:00 Bi-Daily article generation...");
  generateAndSaveArticles(true); // pass flag to filter for Bi-Daily only if needed
});

// For testing: You can trigger this via an internal API if needed
app.get("/api/trigger-cron", async (req, res) => {
  await generateAndSaveArticles();
  res.json({ message: "Cron task triggered manually" });
});

async function startServer() {
  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
