import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import cron from "node-cron";
import { GoogleGenAI } from "@google/genai";
import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";

// Initialize Firebase Admin
// Note: In this environment, we usually rely on environmental credentials 
// or the provided firestore config. Since we are in AIS, we can use the config.
import firebaseConfig from "./firebase-applet-config.json";

const app = express();
const PORT = 3000;

// Initialize Admin SDK
// AIS typically provides a way to interact with Firestore via admin sdk if properly configured
// For this environment, we'll assume the default credentials are available or we use the project ID
initializeApp({
  projectId: firebaseConfig.projectId,
});

const db = getFirestore();

async function generateAndSaveArticles() {
  console.log("Starting daily article generation task...");
  try {
    const userBlogsRef = db.collection('user_blogs');
    const snapshot = await userBlogsRef.where('autoPublish', '==', true).where('schedule', '==', 'Daily').get();
    
    if (snapshot.empty) {
      console.log("No blogs scheduled for daily auto-publish.");
      return;
    }

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

    for (const doc of snapshot.docs) {
      const blog = doc.data();
      console.log(`Generating article for blog: ${blog.name} (User: ${blog.userId})`);

      const prompt = `Write a professional blog post for a blog titled "${blog.name}". 
      Topic: ${blog.topic || 'General Technology'}. 
      Keywords: ${blog.keywords || 'none'}. 
      Tone: ${blog.tone || 'Professional'}. 
      Language: ${blog.language || 'Arabic'}. 
      Format the output as JSON with "title" and "content" (HTML format for content) keys.`;

      try {
        const result = await ai.models.generateContent({
          model: "gemini-1.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json"
          }
        });
        
        const text = result.text;
        
        // Clean up markdown if AI returned it
        const jsonStr = text.replace(/```json|```/g, "").trim();
        const { title, content } = JSON.parse(jsonStr);

        // Save to articles collection
        await db.collection('articles').add({
          title,
          content,
          blogId: blog.blogId,
          blogName: blog.name,
          userId: blog.userId,
          status: 'draft', // Saved as draft because we need user token to publish to Blogger
          isAutoGenerated: true,
          createdAt: FieldValue.serverTimestamp()
        });

        console.log(`Successfully generated and saved article for ${blog.name}`);
      } catch (err) {
        console.error(`Error generating article for ${blog.name}:`, err);
      }
    }
  } catch (error) {
    console.error("Cron job error:", error);
  }
}

// Schedule task at 00:00 every day
cron.schedule("0 0 * * *", () => {
  generateAndSaveArticles();
});

// For testing: You can trigger this via an internal API if needed
app.get("/api/trigger-cron", async (req, res) => {
  await generateAndSaveArticles();
  res.json({ message: "Cron task triggered manually" });
});

async function startServer() {
  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
